### ISSUE TITLE
Multiple bitbucket user

### ISSUE THREAD

**Issue by efraim14** [Wanchai/FTPbucket#10]
Hello,

Sorry for stupid question, i am new to this and wonder to ask if its possible to make multiple credentials bitbucket user? there are 2 of us working on the same project, and if both of us pushing to the project, we want the ftpbucket recognize both of us and push to the server files.

Thanks

**Comment by Keyj1n** [comment]
Hello there,

you just need the credentials of an account who has access to the repository. The user is unimportant because the webhook will always be triggered by any change.  

-Keyjin
