### ISSUE TITLE
Do you plan to support SFTP?

### ISSUE THREAD

**Issue by pixeljitsu** [Wanchai/FTPbucket#2]
I'd love to use FTPbucket, but I need to SFTP from a HTTPS trigger URL.

**Comment by Wanchai** [comment]
Do you need ssh (SFTP) or just secured ftp with ssl (FTPS)?

The second would be easy. You just need to replace ftp_connect with ftp_ssl_connect().
The first would be a bit more tricky.

In both case, I would like to add it, but as of now, I don't have SSH accessible servers or a SSL certificate to test it.
But if you want to do it, you could first try the script as it is or modify it for compatibility. I would be glad to assist you in this path.

**Comment by Wanchai** [comment]
Just created a branch to test SSH. https://github.com/Wanchai/FTPbucket/tree/TestSSH

It only works with BB webhooks.

In the config file, you need to replace 'type'=>'ftp' by 'type'=>'ssh'. The rest of the install is the same.

Tell me if it works for you.

**Comment by pixeljitsu** [comment]
Thanks a bunch,  still having and issue, the logplayload.txt has entries like this:
20.11.2015, 14:43:35: Array

**Comment by Wanchai** [comment]
What does logfile.txt does say?

**Comment by pixeljitsu** [comment]
20.11.2015, 14:50:27: error: Can't find any repo with the name {myusername} for BitBucket in your config file.

**Comment by Wanchai** [comment]
Hi, you can use the latest release.
Start from a clean install.
If you want to copy your files on the same server, you don't need FTP or SSH. Just put  'type'=>'none' (see config.php.sample)
In your case, you need to use that (type>none) because SSH for PHP is not installed on your server.
