### ISSUE TITLE
Push with multiple commits to 1 file uploads the file multiple times

### ISSUE THREAD

**Issue by d2roth** [Wanchai/FTPbucket#20]
Hey @Wanchai,
I use the BBJson.php version of your script and I have noticed that if I make 5 commits to the same file before I push it up the file will be uploaded 5 times, one for each commit. To me, this is really inefficient so I have been trying to come up with a solution. 

I don't have a full solution yet but I am thinking to solve the problem would require changing `ksort($this->data->branch[$branch_name]['commits']);` to use krsort. Then when the files are actually uploaded, in `load_files()` if the file has been previously uploaded skip it. So change `foreach ($commit['files'] as $file) {` to something like:
```PHP
foreach ($commit['files'] as $file) {
  // Check if the file has been handled already
  if(isset($files_handled[$file['file']])){
    continue;
  } else {
    $files_handled[$file['file']] = 1;
  }
  /* ... */
}
```
The `$files_handled ` array would be initialized just after `load_files()` is opened.

Do you think this would help?

**Comment by Wanchai** [comment]
That's a great performance improvement indeed!
