### ISSUE TITLE
update ?

### ISSUE THREAD

**Issue by marco76tv** [Wanchai/FTPbucket#22]
it's a long time from last update, and now don't work

**Comment by vhstrejo** [comment]
Is long time from last update, but still working, maybe you should update your htaccess file to something like this:

`
SetEnv PHP_VER 5

# https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html
# allow POST from bitbucket only

<Limit POST>
	order deny,allow
	deny from all
	allow from 131.103.20.160/27
	allow from 165.254.145.0/26
	allow from 104.192.143.0/24
	allow from 104.192.136.0/21
	allow from 34.198.203.127
	allow from 34.198.178.64
	allow from 34.198.32.85
	allow from 18.205.93.0/25
	allow from 18.234.32.128/25
	allow from 13.52.5.0/25
</Limit>
`

**Comment by vhstrejo** [comment]
Is long time from last update, but still working, maybe you should update your htaccess file to something like this:

``` 
SetEnv PHP_VER 5

# https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html
# allow POST from bitbucket only

<Limit POST>
	order deny,allow
	deny from all
	allow from 131.103.20.160/27
	allow from 165.254.145.0/26
	allow from 104.192.143.0/24
	allow from 104.192.136.0/21
	allow from 34.198.203.127
	allow from 34.198.178.64
	allow from 34.198.32.85
	allow from 18.205.93.0/25
	allow from 18.234.32.128/25
	allow from 13.52.5.0/25
</Limit>
```
