### ISSUE TITLE
Cant't get lists of commits! HTTP_CODE: 401 cURL error

### ISSUE THREAD

**Issue by crisblanco** [Wanchai/FTPbucket#23]
I've just got back from being a while offline. I've tried using FTPbucket, however it's no longer working as it now throws the following error:

"**Cant't get lists of commits! HTTP_CODE: 401 cURL error:**"  (without specifying the cURL error) whenever a push is done. This happens both in new setups and in projects that were working fine last year.

Unfortunately I'm not versed on PHP or the intricacies of BitBucket so I can tinker a little bit, do you (or anyone in the community) have a chance to look into it?  

Could it be related to the way BitBucket now handles permissions in anyway?

Thank you very much

**Comment by Wanchai** [comment]
Have you changed your password for BB ?
