### ISSUE TITLE
Repo Name Issue

### ISSUE THREAD

**Issue by cdemetriadis** [Wanchai/FTPbucket#4]
There seems to be an issue with the payload repo name. Bitbucket does not post the URL slug ("repo-name") as the repo name, rather it sends the actual name ("Repo Name"). This is a big problem when your repo name has spaces. On line 145 when trying to match both names, they'll never be the same. 

Example:
*Slug: repo-name*
*Actual name: Repo Name*
```
strtolower($pl_repo_name) == strtolower($repo['repo_name'])
"repo-name" == "repo name"
```

**Comment by Wanchai** [comment]
Sorry it took me so long ;)

**Comment by cdemetriadis** [comment]
@Wanchai No worries. Thanks for creating the script in the first place!
