### ISSUE TITLE
 Repository xmon/TestWebsite not found

### ISSUE THREAD

**Issue by xmon** [Wanchai/FTPbucket#5]
Hi,

I'm trying to deploy with your code from BitBucket private repository.

In log:
- 18.02.2016, 16:31:57: Script called for a BitBucket JSON payload
- 18.02.2016, 16:31:57: Received a push from {TestWebsite}
- 18.02.2016, 16:31:57: Modifications detected on the branch {desarrollo}
- 18.02.2016, 16:31:57: Transfer done for branch {desarrollo}

But no files are transfer.

debugging I get:
```php
    List of files: Array
    (
        [error] => Array
            (
                [message] => Repository xmon/TestWebsite not found
            )
    )
```

This is my config.php
```php
    return array(
    'repos' => array(
        'repo1' => array(
            'repo_name' => 'TestWebsite',
            'repo_host' => 'bitbucket',
            'branches' => array(
                array(
                    'branch_name' => 'desarrollo',
                    'type' => 'none',
                    'ftp_path' => '../../',
                )
            ),
        ),
    ),
    // Your BitBucket Credentials
    'bitbucket' => array(
        'username' => 'xmon',
        'password' => 'my-password'
    ),
    // ADMIN password for FTPBucket's UI
    'admin_pass' => '12345'
        )

```

My repo, is created under Team, **Test Team**, with Team ID: **testteam**.

The repo URL is like **https://bitbucket.org/testteam/testwebsite**

Any idea to solve it?

thanks in advance

**Comment by solosik** [comment]
Same problem here. @Wanchai or @xmon do you have any suggestions? Is this script working with the latest BB WebHooks? Thank you.

**Comment by xmon** [comment]
Hi @solosik 

I think is working with latest BB WebHooks.
Maybe the problem is the difference between user name to login, and Team repository owner.

the script build the project URL with auth user name.

this is only a idea, I would need to make more tests.

any ideas are welcome.

**Comment by solosik** [comment]
@xmon @Wanchai hello again guys, I think I found the problem.

It's as always in the Repository name, you should use **lowercase only** in your config file.

So @xmon just try to replace 'TestWebsite' to 'testwebsite' and it should work. As it works for me.

@Wanchai please add some additional checks or just add some info into your docs, because as I can see it's already the second issue with Repo names, however thanks a lot for your work & help.

**Comment by Wanchai** [comment]
Please, make more tests and tell me if it's working.
Thanks for your feedback.
