### ISSUE TITLE
PAYLOAD not supported

### ISSUE THREAD

**Issue by stevenspinoza** [Wanchai/FTPbucket#7]
Hi,
I have received PAYLOAD not supported. I have followed the installation, modified the config file and have green light from Bitbucket.

Thanks.

**Comment by Wanchai** [comment]
Did you use the Service or the Webhook?

**Comment by stevenspinoza** [comment]
Webhook. Do you know a simpler way to push/deploy?

**Comment by septoctobre** [comment]
Hi,
Same thing for me : "PAYLOAD not supported" with webhooks.
Everything was working fine till 23/03.

**Comment by shahroq** [comment]
It seems bitbucket only run requests to .com domain, have anybody else noticed this issue?

**Comment by kharbandavikram** [comment]
I am getting same issue. Payload not supported. How to resolve this issue. Can you please confirm
