### ISSUE TITLE
Get 'Cant't get lists of files! cURL error:'

### ISSUE THREAD

**Issue by Keyj1n** [Wanchai/FTPbucket#8]
Hello there,

can you tell me please why this error comes?
- modification of the repo was detected
- username and password are correct
- $url seems correct

its a private repo and im using bitbucket

`
13.03.2016, 22:03:01: Script called for a BitBucket JSON payload
13.03.2016, 22:03:01: Received a push from {ks_website}
13.03.2016, 22:03:01: Modifications detected on the branch {master}
13.03.2016, 22:03:01: Cant't get lists of files! cURL error: 
`

Keyjin

**Comment by Keyj1n** [comment]
ow... find a log failure
Line 209 you must output $ch instead of $cu

Keyjin

**Comment by Keyj1n** [comment]
ok with the right logging i fount out that i have to add the right curl certification in the php.ini
Take a lookt at here:
http://tzfrs.de/2014/07/fix-it-the-right-way-ssl-error-unable-to-get-local-issuer-certificate/

**Comment by Wanchai** [comment]
Thanks for the log fix.
